// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Battle.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MokomoGames.Protobuf {

  /// <summary>Holder for reflection information generated from Battle.proto</summary>
  public static partial class BattleReflection {

    #region Descriptor
    /// <summary>File descriptor for Battle.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BattleReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxCYXR0bGUucHJvdG8SBWVjaXR5KlgKCUF0dHJpYnV0ZRIVChFBVFRSSUJV",
            "VEVfVU5LTk9XThAAEggKBEZJUkUQARIJCgVXQVRFUhACEggKBFdPT0QQAxIJ",
            "CgVMSUdIVBAEEgoKBlNIQURPVxAFKqYBCghTb3VsVHlwZRIUChBTT1VMVFlQ",
            "RV9VTktOT1dOEAASBwoDQVJUEAESDwoLVU5ERVJHUk9VTkQQAhIICgRDVVJF",
            "EAMSDQoJVE9VR0hORVNTEAQSEQoNVFJBTlNDRU5ERU5DRRAFEgsKB0JBTEFO",
            "Q0UQBhIYChRSRUlORk9SQ0VEX1NZTlRIRVNJUxAHEg0KCUVWT0xVVElPThAI",
            "EggKBFNBTEUQCUIXqgIUTW9rb21vR2FtZXMuUHJvdG9idWZiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MokomoGames.Protobuf.Attribute), typeof(global::MokomoGames.Protobuf.SoulType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum Attribute {
    [pbr::OriginalName("ATTRIBUTE_UNKNOWN")] Unknown = 0,
    [pbr::OriginalName("FIRE")] Fire = 1,
    [pbr::OriginalName("WATER")] Water = 2,
    [pbr::OriginalName("WOOD")] Wood = 3,
    [pbr::OriginalName("LIGHT")] Light = 4,
    [pbr::OriginalName("SHADOW")] Shadow = 5,
  }

  public enum SoulType {
    [pbr::OriginalName("SOULTYPE_UNKNOWN")] Unknown = 0,
    [pbr::OriginalName("ART")] Art = 1,
    [pbr::OriginalName("UNDERGROUND")] Underground = 2,
    [pbr::OriginalName("CURE")] Cure = 3,
    [pbr::OriginalName("TOUGHNESS")] Toughness = 4,
    [pbr::OriginalName("TRANSCENDENCE")] Transcendence = 5,
    [pbr::OriginalName("BALANCE")] Balance = 6,
    [pbr::OriginalName("REINFORCED_SYNTHESIS")] ReinforcedSynthesis = 7,
    [pbr::OriginalName("EVOLUTION")] Evolution = 8,
    [pbr::OriginalName("SALE")] Sale = 9,
  }

  #endregion

}

#endregion Designer generated code
