// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: SoulSaveData.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MokomoGames.Protobuf {

  /// <summary>Holder for reflection information generated from SoulSaveData.proto</summary>
  public static partial class SoulSaveDataReflection {

    #region Descriptor
    /// <summary>File descriptor for SoulSaveData.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SoulSaveDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJTb3VsU2F2ZURhdGEucHJvdG8SBWVjaXR5Il8KDFVzZXJTb3VsRGF0YRIM",
            "CgRndWlkGAEgASgJEg8KB3NvdWxfbm8YAiABKA0SFwoPdG90YWxfbGV2ZWxf",
            "ZXhwGAMgASgNEhcKD3RvdGFsX3NraWxsX2V4cBgEIAEoDSI2ChBVc2VyU291",
            "bERhdGFMaXN0EiIKBXNvdWxzGAEgAygLMhMuZWNpdHkuVXNlclNvdWxEYXRh",
            "Ij4KGVVwZGF0ZVVzZXJTb3VsRGF0YVJlcXVlc3QSIQoEc291bBgBIAEoCzIT",
            "LmVjaXR5LlVzZXJTb3VsRGF0YSJAChpVcGRhdGVVc2VyU291bERhdGFSZXNw",
            "b25zZRIiCgVzb3VscxgBIAMoCzITLmVjaXR5LlVzZXJTb3VsRGF0YSIcChpH",
            "ZXRVc2VyU291bERhdGFMaXN0UmVxdWVzdCJBChtHZXRVc2VyU291bERhdGFM",
            "aXN0UmVzcG9uc2USIgoFc291bHMYASADKAsyEy5lY2l0eS5Vc2VyU291bERh",
            "dGFCF6oCFE1va29tb0dhbWVzLlByb3RvYnVmYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MokomoGames.Protobuf.UserSoulData), global::MokomoGames.Protobuf.UserSoulData.Parser, new[]{ "Guid", "SoulNo", "TotalLevelExp", "TotalSkillExp" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MokomoGames.Protobuf.UserSoulDataList), global::MokomoGames.Protobuf.UserSoulDataList.Parser, new[]{ "Souls" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MokomoGames.Protobuf.UpdateUserSoulDataRequest), global::MokomoGames.Protobuf.UpdateUserSoulDataRequest.Parser, new[]{ "Soul" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MokomoGames.Protobuf.UpdateUserSoulDataResponse), global::MokomoGames.Protobuf.UpdateUserSoulDataResponse.Parser, new[]{ "Souls" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MokomoGames.Protobuf.GetUserSoulDataListRequest), global::MokomoGames.Protobuf.GetUserSoulDataListRequest.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MokomoGames.Protobuf.GetUserSoulDataListResponse), global::MokomoGames.Protobuf.GetUserSoulDataListResponse.Parser, new[]{ "Souls" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class UserSoulData : pb::IMessage<UserSoulData> {
    private static readonly pb::MessageParser<UserSoulData> _parser = new pb::MessageParser<UserSoulData>(() => new UserSoulData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UserSoulData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MokomoGames.Protobuf.SoulSaveDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserSoulData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserSoulData(UserSoulData other) : this() {
      guid_ = other.guid_;
      soulNo_ = other.soulNo_;
      totalLevelExp_ = other.totalLevelExp_;
      totalSkillExp_ = other.totalSkillExp_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserSoulData Clone() {
      return new UserSoulData(this);
    }

    /// <summary>Field number for the "guid" field.</summary>
    public const int GuidFieldNumber = 1;
    private string guid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Guid {
      get { return guid_; }
      set {
        guid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "soul_no" field.</summary>
    public const int SoulNoFieldNumber = 2;
    private uint soulNo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint SoulNo {
      get { return soulNo_; }
      set {
        soulNo_ = value;
      }
    }

    /// <summary>Field number for the "total_level_exp" field.</summary>
    public const int TotalLevelExpFieldNumber = 3;
    private uint totalLevelExp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint TotalLevelExp {
      get { return totalLevelExp_; }
      set {
        totalLevelExp_ = value;
      }
    }

    /// <summary>Field number for the "total_skill_exp" field.</summary>
    public const int TotalSkillExpFieldNumber = 4;
    private uint totalSkillExp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint TotalSkillExp {
      get { return totalSkillExp_; }
      set {
        totalSkillExp_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UserSoulData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UserSoulData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Guid != other.Guid) return false;
      if (SoulNo != other.SoulNo) return false;
      if (TotalLevelExp != other.TotalLevelExp) return false;
      if (TotalSkillExp != other.TotalSkillExp) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Guid.Length != 0) hash ^= Guid.GetHashCode();
      if (SoulNo != 0) hash ^= SoulNo.GetHashCode();
      if (TotalLevelExp != 0) hash ^= TotalLevelExp.GetHashCode();
      if (TotalSkillExp != 0) hash ^= TotalSkillExp.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Guid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Guid);
      }
      if (SoulNo != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(SoulNo);
      }
      if (TotalLevelExp != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(TotalLevelExp);
      }
      if (TotalSkillExp != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(TotalSkillExp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Guid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Guid);
      }
      if (SoulNo != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SoulNo);
      }
      if (TotalLevelExp != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(TotalLevelExp);
      }
      if (TotalSkillExp != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(TotalSkillExp);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UserSoulData other) {
      if (other == null) {
        return;
      }
      if (other.Guid.Length != 0) {
        Guid = other.Guid;
      }
      if (other.SoulNo != 0) {
        SoulNo = other.SoulNo;
      }
      if (other.TotalLevelExp != 0) {
        TotalLevelExp = other.TotalLevelExp;
      }
      if (other.TotalSkillExp != 0) {
        TotalSkillExp = other.TotalSkillExp;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Guid = input.ReadString();
            break;
          }
          case 16: {
            SoulNo = input.ReadUInt32();
            break;
          }
          case 24: {
            TotalLevelExp = input.ReadUInt32();
            break;
          }
          case 32: {
            TotalSkillExp = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class UserSoulDataList : pb::IMessage<UserSoulDataList> {
    private static readonly pb::MessageParser<UserSoulDataList> _parser = new pb::MessageParser<UserSoulDataList>(() => new UserSoulDataList());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UserSoulDataList> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MokomoGames.Protobuf.SoulSaveDataReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserSoulDataList() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserSoulDataList(UserSoulDataList other) : this() {
      souls_ = other.souls_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserSoulDataList Clone() {
      return new UserSoulDataList(this);
    }

    /// <summary>Field number for the "souls" field.</summary>
    public const int SoulsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::MokomoGames.Protobuf.UserSoulData> _repeated_souls_codec
        = pb::FieldCodec.ForMessage(10, global::MokomoGames.Protobuf.UserSoulData.Parser);
    private readonly pbc::RepeatedField<global::MokomoGames.Protobuf.UserSoulData> souls_ = new pbc::RepeatedField<global::MokomoGames.Protobuf.UserSoulData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::MokomoGames.Protobuf.UserSoulData> Souls {
      get { return souls_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UserSoulDataList);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UserSoulDataList other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!souls_.Equals(other.souls_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= souls_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      souls_.WriteTo(output, _repeated_souls_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += souls_.CalculateSize(_repeated_souls_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UserSoulDataList other) {
      if (other == null) {
        return;
      }
      souls_.Add(other.souls_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            souls_.AddEntriesFrom(input, _repeated_souls_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 通信API
  /// </summary>
  public sealed partial class UpdateUserSoulDataRequest : pb::IMessage<UpdateUserSoulDataRequest> {
    private static readonly pb::MessageParser<UpdateUserSoulDataRequest> _parser = new pb::MessageParser<UpdateUserSoulDataRequest>(() => new UpdateUserSoulDataRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UpdateUserSoulDataRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MokomoGames.Protobuf.SoulSaveDataReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateUserSoulDataRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateUserSoulDataRequest(UpdateUserSoulDataRequest other) : this() {
      soul_ = other.soul_ != null ? other.soul_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateUserSoulDataRequest Clone() {
      return new UpdateUserSoulDataRequest(this);
    }

    /// <summary>Field number for the "soul" field.</summary>
    public const int SoulFieldNumber = 1;
    private global::MokomoGames.Protobuf.UserSoulData soul_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MokomoGames.Protobuf.UserSoulData Soul {
      get { return soul_; }
      set {
        soul_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UpdateUserSoulDataRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UpdateUserSoulDataRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Soul, other.Soul)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (soul_ != null) hash ^= Soul.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (soul_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Soul);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (soul_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Soul);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UpdateUserSoulDataRequest other) {
      if (other == null) {
        return;
      }
      if (other.soul_ != null) {
        if (soul_ == null) {
          Soul = new global::MokomoGames.Protobuf.UserSoulData();
        }
        Soul.MergeFrom(other.Soul);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (soul_ == null) {
              Soul = new global::MokomoGames.Protobuf.UserSoulData();
            }
            input.ReadMessage(Soul);
            break;
          }
        }
      }
    }

  }

  public sealed partial class UpdateUserSoulDataResponse : pb::IMessage<UpdateUserSoulDataResponse> {
    private static readonly pb::MessageParser<UpdateUserSoulDataResponse> _parser = new pb::MessageParser<UpdateUserSoulDataResponse>(() => new UpdateUserSoulDataResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UpdateUserSoulDataResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MokomoGames.Protobuf.SoulSaveDataReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateUserSoulDataResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateUserSoulDataResponse(UpdateUserSoulDataResponse other) : this() {
      souls_ = other.souls_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateUserSoulDataResponse Clone() {
      return new UpdateUserSoulDataResponse(this);
    }

    /// <summary>Field number for the "souls" field.</summary>
    public const int SoulsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::MokomoGames.Protobuf.UserSoulData> _repeated_souls_codec
        = pb::FieldCodec.ForMessage(10, global::MokomoGames.Protobuf.UserSoulData.Parser);
    private readonly pbc::RepeatedField<global::MokomoGames.Protobuf.UserSoulData> souls_ = new pbc::RepeatedField<global::MokomoGames.Protobuf.UserSoulData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::MokomoGames.Protobuf.UserSoulData> Souls {
      get { return souls_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UpdateUserSoulDataResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UpdateUserSoulDataResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!souls_.Equals(other.souls_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= souls_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      souls_.WriteTo(output, _repeated_souls_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += souls_.CalculateSize(_repeated_souls_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UpdateUserSoulDataResponse other) {
      if (other == null) {
        return;
      }
      souls_.Add(other.souls_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            souls_.AddEntriesFrom(input, _repeated_souls_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetUserSoulDataListRequest : pb::IMessage<GetUserSoulDataListRequest> {
    private static readonly pb::MessageParser<GetUserSoulDataListRequest> _parser = new pb::MessageParser<GetUserSoulDataListRequest>(() => new GetUserSoulDataListRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetUserSoulDataListRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MokomoGames.Protobuf.SoulSaveDataReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetUserSoulDataListRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetUserSoulDataListRequest(GetUserSoulDataListRequest other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetUserSoulDataListRequest Clone() {
      return new GetUserSoulDataListRequest(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetUserSoulDataListRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetUserSoulDataListRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetUserSoulDataListRequest other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  public sealed partial class GetUserSoulDataListResponse : pb::IMessage<GetUserSoulDataListResponse> {
    private static readonly pb::MessageParser<GetUserSoulDataListResponse> _parser = new pb::MessageParser<GetUserSoulDataListResponse>(() => new GetUserSoulDataListResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetUserSoulDataListResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MokomoGames.Protobuf.SoulSaveDataReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetUserSoulDataListResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetUserSoulDataListResponse(GetUserSoulDataListResponse other) : this() {
      souls_ = other.souls_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetUserSoulDataListResponse Clone() {
      return new GetUserSoulDataListResponse(this);
    }

    /// <summary>Field number for the "souls" field.</summary>
    public const int SoulsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::MokomoGames.Protobuf.UserSoulData> _repeated_souls_codec
        = pb::FieldCodec.ForMessage(10, global::MokomoGames.Protobuf.UserSoulData.Parser);
    private readonly pbc::RepeatedField<global::MokomoGames.Protobuf.UserSoulData> souls_ = new pbc::RepeatedField<global::MokomoGames.Protobuf.UserSoulData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::MokomoGames.Protobuf.UserSoulData> Souls {
      get { return souls_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetUserSoulDataListResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetUserSoulDataListResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!souls_.Equals(other.souls_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= souls_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      souls_.WriteTo(output, _repeated_souls_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += souls_.CalculateSize(_repeated_souls_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetUserSoulDataListResponse other) {
      if (other == null) {
        return;
      }
      souls_.Add(other.souls_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            souls_.AddEntriesFrom(input, _repeated_souls_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
