// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: UserData.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MokomoGames.Protobuf {

  /// <summary>Holder for reflection information generated from UserData.proto</summary>
  public static partial class UserDataReflection {

    #region Descriptor
    /// <summary>File descriptor for UserData.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UserDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5Vc2VyRGF0YS5wcm90bxIFZWNpdHkiJAoUVXBkYXRlU3RhbWluYVJlcXVl",
            "c3QSDAoEZGlmZhgBIAEoBSIvChVVcGRhdGVTdGFtaW5hUmVzcG9uc2USFgoO",
            "Y3VycmVudFN0YW1pbmEYASABKA0iRAoZR2V0UGxheWVyU2F2ZURhdGFSZXNw",
            "b25zZRInCghzYXZlRGF0YRgBIAEoCzIVLmVjaXR5LlBsYXllclNhdmVEYXRh",
            "IiIKIFJlY292ZXJ5U3RhbWluYUJ5V2FpdFRpbWVSZXF1ZXN0Ij4KIVJlY292",
            "ZXJ5U3RhbWluYUJ5V2FpdFRpbWVSZXNwb25zZRIZChFyZWNvdmVyaWVkU3Rh",
            "bWluYRgBIAEoDSJpCg5QbGF5ZXJTYXZlRGF0YRIPCgdzdGFtaW5hGAEgASgN",
            "Eg8KB3l1a2ljaGkYAiABKA0SDAoEY29pbhgDIAEoDRIMCgRtaXp1GAQgASgN",
            "EgwKBHJhbmsYBSABKA0SCwoDZXhwGAYgASgNIi0KHVJlY292ZXJ5RnVlbEJ5",
            "WXVraWNoaVJlc3BvbnNlEgwKBGZ1ZWwYASABKA1CF6oCFE1va29tb0dhbWVz",
            "LlByb3RvYnVmYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MokomoGames.Protobuf.UpdateStaminaRequest), global::MokomoGames.Protobuf.UpdateStaminaRequest.Parser, new[]{ "Diff" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MokomoGames.Protobuf.UpdateStaminaResponse), global::MokomoGames.Protobuf.UpdateStaminaResponse.Parser, new[]{ "CurrentStamina" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MokomoGames.Protobuf.GetPlayerSaveDataResponse), global::MokomoGames.Protobuf.GetPlayerSaveDataResponse.Parser, new[]{ "SaveData" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MokomoGames.Protobuf.RecoveryStaminaByWaitTimeRequest), global::MokomoGames.Protobuf.RecoveryStaminaByWaitTimeRequest.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MokomoGames.Protobuf.RecoveryStaminaByWaitTimeResponse), global::MokomoGames.Protobuf.RecoveryStaminaByWaitTimeResponse.Parser, new[]{ "RecoveriedStamina" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MokomoGames.Protobuf.PlayerSaveData), global::MokomoGames.Protobuf.PlayerSaveData.Parser, new[]{ "Stamina", "Yukichi", "Coin", "Mizu", "Rank", "Exp" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MokomoGames.Protobuf.RecoveryFuelByYukichiResponse), global::MokomoGames.Protobuf.RecoveryFuelByYukichiResponse.Parser, new[]{ "Fuel" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class UpdateStaminaRequest : pb::IMessage<UpdateStaminaRequest> {
    private static readonly pb::MessageParser<UpdateStaminaRequest> _parser = new pb::MessageParser<UpdateStaminaRequest>(() => new UpdateStaminaRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UpdateStaminaRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MokomoGames.Protobuf.UserDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateStaminaRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateStaminaRequest(UpdateStaminaRequest other) : this() {
      diff_ = other.diff_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateStaminaRequest Clone() {
      return new UpdateStaminaRequest(this);
    }

    /// <summary>Field number for the "diff" field.</summary>
    public const int DiffFieldNumber = 1;
    private int diff_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Diff {
      get { return diff_; }
      set {
        diff_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UpdateStaminaRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UpdateStaminaRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Diff != other.Diff) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Diff != 0) hash ^= Diff.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Diff != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Diff);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Diff != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Diff);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UpdateStaminaRequest other) {
      if (other == null) {
        return;
      }
      if (other.Diff != 0) {
        Diff = other.Diff;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Diff = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class UpdateStaminaResponse : pb::IMessage<UpdateStaminaResponse> {
    private static readonly pb::MessageParser<UpdateStaminaResponse> _parser = new pb::MessageParser<UpdateStaminaResponse>(() => new UpdateStaminaResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UpdateStaminaResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MokomoGames.Protobuf.UserDataReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateStaminaResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateStaminaResponse(UpdateStaminaResponse other) : this() {
      currentStamina_ = other.currentStamina_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateStaminaResponse Clone() {
      return new UpdateStaminaResponse(this);
    }

    /// <summary>Field number for the "currentStamina" field.</summary>
    public const int CurrentStaminaFieldNumber = 1;
    private uint currentStamina_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint CurrentStamina {
      get { return currentStamina_; }
      set {
        currentStamina_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UpdateStaminaResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UpdateStaminaResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CurrentStamina != other.CurrentStamina) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (CurrentStamina != 0) hash ^= CurrentStamina.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (CurrentStamina != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(CurrentStamina);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (CurrentStamina != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CurrentStamina);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UpdateStaminaResponse other) {
      if (other == null) {
        return;
      }
      if (other.CurrentStamina != 0) {
        CurrentStamina = other.CurrentStamina;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            CurrentStamina = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetPlayerSaveDataResponse : pb::IMessage<GetPlayerSaveDataResponse> {
    private static readonly pb::MessageParser<GetPlayerSaveDataResponse> _parser = new pb::MessageParser<GetPlayerSaveDataResponse>(() => new GetPlayerSaveDataResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetPlayerSaveDataResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MokomoGames.Protobuf.UserDataReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetPlayerSaveDataResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetPlayerSaveDataResponse(GetPlayerSaveDataResponse other) : this() {
      saveData_ = other.saveData_ != null ? other.saveData_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetPlayerSaveDataResponse Clone() {
      return new GetPlayerSaveDataResponse(this);
    }

    /// <summary>Field number for the "saveData" field.</summary>
    public const int SaveDataFieldNumber = 1;
    private global::MokomoGames.Protobuf.PlayerSaveData saveData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MokomoGames.Protobuf.PlayerSaveData SaveData {
      get { return saveData_; }
      set {
        saveData_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetPlayerSaveDataResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetPlayerSaveDataResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(SaveData, other.SaveData)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (saveData_ != null) hash ^= SaveData.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (saveData_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(SaveData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (saveData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SaveData);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetPlayerSaveDataResponse other) {
      if (other == null) {
        return;
      }
      if (other.saveData_ != null) {
        if (saveData_ == null) {
          SaveData = new global::MokomoGames.Protobuf.PlayerSaveData();
        }
        SaveData.MergeFrom(other.SaveData);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (saveData_ == null) {
              SaveData = new global::MokomoGames.Protobuf.PlayerSaveData();
            }
            input.ReadMessage(SaveData);
            break;
          }
        }
      }
    }

  }

  public sealed partial class RecoveryStaminaByWaitTimeRequest : pb::IMessage<RecoveryStaminaByWaitTimeRequest> {
    private static readonly pb::MessageParser<RecoveryStaminaByWaitTimeRequest> _parser = new pb::MessageParser<RecoveryStaminaByWaitTimeRequest>(() => new RecoveryStaminaByWaitTimeRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RecoveryStaminaByWaitTimeRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MokomoGames.Protobuf.UserDataReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RecoveryStaminaByWaitTimeRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RecoveryStaminaByWaitTimeRequest(RecoveryStaminaByWaitTimeRequest other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RecoveryStaminaByWaitTimeRequest Clone() {
      return new RecoveryStaminaByWaitTimeRequest(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RecoveryStaminaByWaitTimeRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RecoveryStaminaByWaitTimeRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RecoveryStaminaByWaitTimeRequest other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  public sealed partial class RecoveryStaminaByWaitTimeResponse : pb::IMessage<RecoveryStaminaByWaitTimeResponse> {
    private static readonly pb::MessageParser<RecoveryStaminaByWaitTimeResponse> _parser = new pb::MessageParser<RecoveryStaminaByWaitTimeResponse>(() => new RecoveryStaminaByWaitTimeResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RecoveryStaminaByWaitTimeResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MokomoGames.Protobuf.UserDataReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RecoveryStaminaByWaitTimeResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RecoveryStaminaByWaitTimeResponse(RecoveryStaminaByWaitTimeResponse other) : this() {
      recoveriedStamina_ = other.recoveriedStamina_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RecoveryStaminaByWaitTimeResponse Clone() {
      return new RecoveryStaminaByWaitTimeResponse(this);
    }

    /// <summary>Field number for the "recoveriedStamina" field.</summary>
    public const int RecoveriedStaminaFieldNumber = 1;
    private uint recoveriedStamina_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint RecoveriedStamina {
      get { return recoveriedStamina_; }
      set {
        recoveriedStamina_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RecoveryStaminaByWaitTimeResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RecoveryStaminaByWaitTimeResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RecoveriedStamina != other.RecoveriedStamina) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (RecoveriedStamina != 0) hash ^= RecoveriedStamina.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (RecoveriedStamina != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(RecoveriedStamina);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (RecoveriedStamina != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RecoveriedStamina);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RecoveryStaminaByWaitTimeResponse other) {
      if (other == null) {
        return;
      }
      if (other.RecoveriedStamina != 0) {
        RecoveriedStamina = other.RecoveriedStamina;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            RecoveriedStamina = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class PlayerSaveData : pb::IMessage<PlayerSaveData> {
    private static readonly pb::MessageParser<PlayerSaveData> _parser = new pb::MessageParser<PlayerSaveData>(() => new PlayerSaveData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PlayerSaveData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MokomoGames.Protobuf.UserDataReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerSaveData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerSaveData(PlayerSaveData other) : this() {
      stamina_ = other.stamina_;
      yukichi_ = other.yukichi_;
      coin_ = other.coin_;
      mizu_ = other.mizu_;
      rank_ = other.rank_;
      exp_ = other.exp_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerSaveData Clone() {
      return new PlayerSaveData(this);
    }

    /// <summary>Field number for the "stamina" field.</summary>
    public const int StaminaFieldNumber = 1;
    private uint stamina_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Stamina {
      get { return stamina_; }
      set {
        stamina_ = value;
      }
    }

    /// <summary>Field number for the "yukichi" field.</summary>
    public const int YukichiFieldNumber = 2;
    private uint yukichi_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Yukichi {
      get { return yukichi_; }
      set {
        yukichi_ = value;
      }
    }

    /// <summary>Field number for the "coin" field.</summary>
    public const int CoinFieldNumber = 3;
    private uint coin_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Coin {
      get { return coin_; }
      set {
        coin_ = value;
      }
    }

    /// <summary>Field number for the "mizu" field.</summary>
    public const int MizuFieldNumber = 4;
    private uint mizu_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Mizu {
      get { return mizu_; }
      set {
        mizu_ = value;
      }
    }

    /// <summary>Field number for the "rank" field.</summary>
    public const int RankFieldNumber = 5;
    private uint rank_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Rank {
      get { return rank_; }
      set {
        rank_ = value;
      }
    }

    /// <summary>Field number for the "exp" field.</summary>
    public const int ExpFieldNumber = 6;
    private uint exp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Exp {
      get { return exp_; }
      set {
        exp_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PlayerSaveData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PlayerSaveData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Stamina != other.Stamina) return false;
      if (Yukichi != other.Yukichi) return false;
      if (Coin != other.Coin) return false;
      if (Mizu != other.Mizu) return false;
      if (Rank != other.Rank) return false;
      if (Exp != other.Exp) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Stamina != 0) hash ^= Stamina.GetHashCode();
      if (Yukichi != 0) hash ^= Yukichi.GetHashCode();
      if (Coin != 0) hash ^= Coin.GetHashCode();
      if (Mizu != 0) hash ^= Mizu.GetHashCode();
      if (Rank != 0) hash ^= Rank.GetHashCode();
      if (Exp != 0) hash ^= Exp.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Stamina != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Stamina);
      }
      if (Yukichi != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Yukichi);
      }
      if (Coin != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Coin);
      }
      if (Mizu != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Mizu);
      }
      if (Rank != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(Rank);
      }
      if (Exp != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(Exp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Stamina != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Stamina);
      }
      if (Yukichi != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Yukichi);
      }
      if (Coin != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Coin);
      }
      if (Mizu != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Mizu);
      }
      if (Rank != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Rank);
      }
      if (Exp != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Exp);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PlayerSaveData other) {
      if (other == null) {
        return;
      }
      if (other.Stamina != 0) {
        Stamina = other.Stamina;
      }
      if (other.Yukichi != 0) {
        Yukichi = other.Yukichi;
      }
      if (other.Coin != 0) {
        Coin = other.Coin;
      }
      if (other.Mizu != 0) {
        Mizu = other.Mizu;
      }
      if (other.Rank != 0) {
        Rank = other.Rank;
      }
      if (other.Exp != 0) {
        Exp = other.Exp;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Stamina = input.ReadUInt32();
            break;
          }
          case 16: {
            Yukichi = input.ReadUInt32();
            break;
          }
          case 24: {
            Coin = input.ReadUInt32();
            break;
          }
          case 32: {
            Mizu = input.ReadUInt32();
            break;
          }
          case 40: {
            Rank = input.ReadUInt32();
            break;
          }
          case 48: {
            Exp = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class RecoveryFuelByYukichiResponse : pb::IMessage<RecoveryFuelByYukichiResponse> {
    private static readonly pb::MessageParser<RecoveryFuelByYukichiResponse> _parser = new pb::MessageParser<RecoveryFuelByYukichiResponse>(() => new RecoveryFuelByYukichiResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RecoveryFuelByYukichiResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MokomoGames.Protobuf.UserDataReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RecoveryFuelByYukichiResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RecoveryFuelByYukichiResponse(RecoveryFuelByYukichiResponse other) : this() {
      fuel_ = other.fuel_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RecoveryFuelByYukichiResponse Clone() {
      return new RecoveryFuelByYukichiResponse(this);
    }

    /// <summary>Field number for the "fuel" field.</summary>
    public const int FuelFieldNumber = 1;
    private uint fuel_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Fuel {
      get { return fuel_; }
      set {
        fuel_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RecoveryFuelByYukichiResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RecoveryFuelByYukichiResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Fuel != other.Fuel) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Fuel != 0) hash ^= Fuel.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Fuel != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Fuel);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Fuel != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Fuel);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RecoveryFuelByYukichiResponse other) {
      if (other == null) {
        return;
      }
      if (other.Fuel != 0) {
        Fuel = other.Fuel;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Fuel = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
